### ISSUE TITLE
XDE project deployment is only partially successful

### ISSUE THREAD

**Issue by andrea-parrilli** [xillio/inbox#13]
Description
1. spin up XDE and three worker services
2. deploy project 1, 
3. check the project folders of the worker services (notice that the deployment is partially successful)
4. deploy project 2, 
5. check the project folders of the worker services (notice that the deployment is partially successful)

Tested with master branch with build/commit ffea975b8d0460d760ad355380a1f86196a910e2

Analysis
The deployer uses a filesystem location to store temp data and the xillball cache.
This location is entirely determined by the project definition being deployed.
When the same project is being deployed more than once concurrently, there is a high chance of the same location being erased or locked by the other threads. This leads to partial deploys and unpredictable cluster state.

Solution
Concurrent deploys using the same resources should be serialized (not run concurrently).

Options
![projects-deployed-mongodb](https://user-images.githubusercontent.com/36929007/36893714-62c4ec80-1e09-11e8-9052-fff3c36ded99.png)
![cluster-state](https://user-images.githubusercontent.com/36929007/36893717-64e98480-1e09-11e8-9e41-819582dd6808.png)
![2ndprojectdeployed](https://user-images.githubusercontent.com/36929007/36893719-67728198-1e09-11e8-8a03-7784b5fad4a1.png)
![1stprojectdeployed](https://user-images.githubusercontent.com/36929007/36893722-69a84b50-1e09-11e8-8862-52d2878f31eb.png)
![1stprojectdeployed_2](https://user-images.githubusercontent.com/36929007/36893725-6bc7a4a8-1e09-11e8-9b33-91f0679eff67.png)

**Comment by nielsrietkerk** [comment]
Created in the wrong place.
